Alpha feb2023
BV-BRC/BV-BRC-Web pull request #544
Opened 2023-02-07 22:11 UTC by mshukla1

2023-02-07 23:43 UTC, olsonanl commented
I don't think the second removals of display:none are correct. the code at https://github.com/BV-BRC/BV-BRC-Web/blob/master/public/js/p3/widget/app/MetagenomicReadMapping.js#L373 manages the visibility of those widgets based on the value of the radio buttons, and the default states appear to be correct. I've not tried the code yet on my own however to verify this.

2023-02-08 19:03 UTC, chris-c-thomas commented on public/js/p3/widget/app/templates/MetagenomicReadMapping.html
> +        <div class="appRow">
Keep this to display the radio buttons

2023-02-08 19:03 UTC, chris-c-thomas commented on public/js/p3/widget/app/templates/MetagenomicReadMapping.html
> +        <div data-dojo-attach-point = "geneSetFastaWidgetBox">
Set back to display: none as handled by the logic

2023-02-08 19:03 UTC, chris-c-thomas commented on public/js/p3/widget/app/templates/MetagenomicReadMapping.html
> +        <div data-dojo-attach-point = "geneSetFeaturegroupWidgetBox">
Set back to display: none as handled by the logic

2023-02-08 19:04 UTC, chris-c-thomas requested changes
@olsonanl is right. Just have the radio buttons display on line 98 and the logic works as expected.

2023-02-09 18:37 UTC, olsonanl approved these changes

2023-02-09 18:38 UTC, olsonanl approved these changes

2023-02-09 18:39 UTC, merged